#
# db config
#
db:
    default:        eCommerce               # default database
    databases:      [ "eCommerce", "test" ] # list of defined databases
    python:
        <<:         *global_db_python       # get the python modules config
    eCommerce:                              # get eCommerce database and overide the host ip
        <<:         *global_db_eCommerce
        host:       192.168.1.105
    test:                                   # get the test database
        <<:         *global_db_test
#
# keychain config
#
keychain:                                   # get the keychain
    <<:             *global_keychain
